#!/usr/bin/env python3
"""
generate-personas.py — bundle the 10 panels + 43 judge personas into the
MCP server, so it can run any named panel (not just the default 5).

Reads the project's authored source of truth:
  - metric-brand-auditor/panels/*.yaml   (panel -> judge slugs + names + language)
  - perspectives/<slug>-perspective/SKILL.md  (each judge's authored persona)

Emits (committed, compiled into dist by tsc):
  - src/llm/panels.generated.ts
  - src/llm/personas.generated.ts

Personas are EXTRACTED from the authored SKILL.md files (front-matter summary +
"Core Mental Models" headings) — never invented. Re-run when panels/personas change:
  python3 packages/mcp-server/scripts/generate-personas.py
"""

import json
import re
import sys
from pathlib import Path

import yaml

PKG = Path(__file__).resolve().parent.parent
REPO = PKG.parent.parent
PANELS_DIR = REPO / "metric-brand-auditor" / "panels"
PERSP_DIR = REPO / "perspectives"
OUT_DIR = PKG / "src" / "llm"

SKIP_PANELS = {"industries.yaml", "README.md"}
HEADER = "// AUTO-GENERATED by packages/mcp-server/scripts/generate-personas.py — do not edit by hand.\n"


def front_matter(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return {}


def clean(s: str) -> str:
    return re.sub(r"\s+", " ", s or "").strip()


def extract_summary(description: str) -> str:
    """First meaningful paragraph of the front-matter description (the lens summary),
    dropping the 'Use as' / 'Explicit triggers' / 'Do not activate' operational notes."""
    if not description:
        return ""
    para = description.split("\n\n")[0]
    para = re.split(r"(Use as|使用场景|Explicit triggers|触发词|Do not activate|不要激活)", para)[0]
    return clean(para)


def extract_models(body: str) -> list:
    """Collect '### Model N: Title' (or similar) headings under a mental-models /
    decision-heuristics section — the judge's decision heuristics in condensed form."""
    m = re.search(
        r"^##\s+(?:Core Mental Models|Mental Models|Decision Heuristics|决策启发式|核心心智模型|核心决策模型)(.*?)(?=^##\s|\Z)",
        body, re.MULTILINE | re.DOTALL,
    )
    section = m.group(1) if m else body
    models = re.findall(r"^###\s+(?:Model\s*\d+\s*[:：]\s*)?(.+)$", section, re.MULTILINE)
    return [clean(t) for t in models][:6]


def build_dna(slug: str, description: str, body: str) -> str:
    summary = extract_summary(description)
    models = extract_models(body)
    dna = summary
    if models:
        dna += "\n决策模型 / Decision models: " + "；".join(models) + "。"
    return dna.strip()


def main() -> int:
    # ── panels ────────────────────────────────────────────────────────────────
    panels: dict = {}
    judge_meta: dict = {}  # slug -> {name_cn, name_en, language}
    for y in sorted(PANELS_DIR.glob("*.yaml")):
        if y.name in SKIP_PANELS:
            continue
        d = yaml.safe_load(y.read_text(encoding="utf-8")) or {}
        name = d.get("name", y.stem)
        judges = d.get("judges") or []
        panels[name] = {
            "name": name,
            "display_name": clean(d.get("display_name", name)),
            "description": clean(d.get("description", "")),
            "judges": [j["slug"] for j in judges],
        }
        for j in judges:
            judge_meta.setdefault(j["slug"], {
                "name_cn": j.get("display_name_cn", j["slug"]),
                "name_en": j.get("display_name_en", j["slug"]),
                "language": "en" if j.get("language") == "en" else "zh",
            })

    # ── personas ──────────────────────────────────────────────────────────────
    personas: dict = {}
    missing, thin = [], []
    for slug, meta in sorted(judge_meta.items()):
        skill = PERSP_DIR / f"{slug}-perspective" / "SKILL.md"
        if not skill.exists():
            missing.append(slug)
            continue
        text = skill.read_text(encoding="utf-8")
        fm = front_matter(text)
        body = text[text.find("\n---\n") + 5:] if "\n---\n" in text else text
        dna = build_dna(slug, fm.get("description", ""), body)
        if len(dna) < 40:
            thin.append(slug)
        personas[slug] = {**meta, "dna": dna}

    # ── write ─────────────────────────────────────────────────────────────────
    panels_ts = (
        HEADER
        + "\nexport interface GeneratedPanel {\n"
          "  name: string;\n  display_name: string;\n  description: string;\n  judges: string[];\n}\n\n"
        + "export const GENERATED_PANELS: Record<string, GeneratedPanel> = "
        + json.dumps(panels, ensure_ascii=False, indent=2)
        + ";\n\n"
        + "export const PANEL_NAMES = ["
        + ", ".join(json.dumps(n) for n in panels)
        + "] as const;\n"
    )
    (OUT_DIR / "panels.generated.ts").write_text(panels_ts, encoding="utf-8")

    personas_ts = (
        HEADER
        + "\nexport interface GeneratedPersona {\n"
          "  name_cn: string;\n  name_en: string;\n  language: 'zh' | 'en';\n  dna: string;\n}\n\n"
        + "export const GENERATED_JUDGES: Record<string, GeneratedPersona> = "
        + json.dumps(personas, ensure_ascii=False, indent=2)
        + ";\n"
    )
    (OUT_DIR / "personas.generated.ts").write_text(personas_ts, encoding="utf-8")

    print(f"panels:   {len(panels)} → src/llm/panels.generated.ts")
    print(f"personas: {len(personas)} → src/llm/personas.generated.ts")
    if missing:
        print(f"WARNING missing SKILL.md: {missing}")
    if thin:
        print(f"WARNING thin DNA (<40 chars): {thin}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
