import type { AuditState } from '../types.js';
import type { FilesystemStore } from '../store/filesystem.js';
import type { LLMClient } from '../llm/client.js';
import { mergeSystemPrompt, mergeUserPrompt } from '../llm/prompts.js';
import { SERVER_VERSION } from '../version.js';

const DEFAULT_JUDGES = ['fusheng', 'jobs', 'likejia', 'wu-jundong', 'zhang-yiming'];

export interface MergeResult {
  report_md: string;
  input_tokens: number;
  output_tokens: number;
}

export async function runPhase5Merge(
  state: AuditState,
  synthesis: string,
  reviews: Record<string, string>,
  store: FilesystemStore,
  client: LLMClient,
  log: (level: string, msg: string) => void,
): Promise<MergeResult> {
  const judges = state.options.judges ?? DEFAULT_JUDGES;
  log('info', `[${state.audit_id}] Phase 5: merging ${Object.keys(reviews).length} reviews into final report`);

  const result = await client.complete(
    mergeSystemPrompt(),
    mergeUserPrompt(state.brand, synthesis, reviews, judges),
    8192,
  );

  const reportHeader = buildReportHeader(state);
  const report_md = reportHeader + result.content + buildLegalFooter();

  await store.writeFile(state.audit_id, 'report.md', report_md);

  // Generate minimal HTML wrapper
  const report_html = buildReportHtml(state, report_md);
  await store.writeFile(state.audit_id, 'report.html', report_html);

  // Write version snapshot
  const versionSlug = `v1_${new Date().toISOString().slice(0, 10)}`;
  await store.writeFile(state.audit_id, `versions/${versionSlug}.md`, report_md);

  return {
    report_md,
    input_tokens: result.input_tokens,
    output_tokens: result.output_tokens,
  };
}

function buildReportHeader(state: AuditState): string {
  return `# ${state.brand} · MBA Audit Report · v1 · ${new Date().toISOString().slice(0, 10)}

> Generated by MBA MCP Server v${SERVER_VERSION}
> Audit ID: \`${state.audit_id}\`
> Panel: ${state.panel}
> Mode: ${state.mode.toUpperCase()}

---

`;
}

function buildLegalFooter(): string {
  return `

---

## Legal / IP / Disclaimer

This report was generated by MBA (Metric Brand Auditor), an AI-powered brand influence audit system. Judge personas are AI simulations based on publicly available information (interviews, articles, speeches) — they represent **plausible analytical perspectives**, not the actual opinions of the named individuals.

- All findings are based on publicly accessible sources only
- No non-public information, commercial secrets, or unauthorized data was used
- Unavailable data is marked N/A rather than estimated
- This report does not constitute investment advice
- Scores reflect the simulated judge panel's assessment at the time of the audit

© 2026 MBA · Metric Brand Auditor · zhanglunet/mba
`;
}

function buildReportHtml(state: AuditState, markdownContent: string): string {
  // Escape HTML in the markdown content
  const escaped = markdownContent
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  return `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${state.brand} · MBA Audit Report</title>
<style>
  :root { --ink: #111; --paper: #faf8f3; --accent: #c1440e; --muted: #6b6760; }
  * { box-sizing: border-box; }
  body { background: var(--paper); color: var(--ink); font-family: ui-serif, Georgia, serif; line-height: 1.65; max-width: 860px; margin: 0 auto; padding: 40px 24px 80px; }
  h1 { font-size: clamp(24px, 4vw, 40px); font-weight: 800; line-height: 1.1; margin: 0 0 16px; }
  h2 { font-size: 22px; font-weight: 700; margin: 40px 0 10px; border-top: 1px solid #1a1a1a; padding-top: 16px; }
  h3 { font-size: 16px; font-weight: 700; margin: 24px 0 8px; color: var(--accent); }
  pre { background: #1a1a1a; color: #f3f1ea; padding: 14px 16px; border-radius: 6px; overflow-x: auto; font-size: 13px; }
  code { font-family: ui-monospace, monospace; font-size: 0.87em; background: #f0ece3; padding: 1px 5px; border-radius: 3px; }
  blockquote { border-left: 4px solid var(--accent); margin: 16px 0; padding: 8px 16px; background: #fff7ed; }
  table { border-collapse: collapse; width: 100%; margin: 14px 0; font-size: 14px; }
  th { background: #1a1a1a; color: #f3f1ea; padding: 8px 12px; text-align: left; }
  td { border: 1px solid #d8d2c6; padding: 7px 12px; }
  .meta { font-family: ui-sans-serif, sans-serif; font-size: 13px; color: var(--muted); margin: 0 0 24px; }
  .disclaimer { border: 1px solid #d8d2c6; border-radius: 4px; padding: 14px 16px; background: #f5f2ec; font-size: 13px; color: var(--muted); margin-top: 40px; }
</style>
</head>
<body>
<div class="meta">MBA MCP Server v${SERVER_VERSION} · Audit ID: <code>${state.audit_id}</code> · Panel: ${state.panel}</div>
<pre>${escaped}</pre>
<p class="disclaimer">This report was generated by MBA (Metric Brand Auditor). Judge personas are AI simulations — not actual opinions of the named individuals. Not investment advice.</p>
</body>
</html>`;
}
